language: node_js
branches:
  only:
  - master
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_65329f5fbcde_key -iv $encrypted_65329f5fbcde_iv
  -in servicesAccounts.tar.enc -out functions/servicesAccounts.tar -d
- tar xvf ./functions/servicesAccounts.tar -C ./functions
- ls ./functions
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
- npm install --force-online
jobs:
  include:
  - stage: Deploy PRE
    if: type = pull_request
    env:
    - NODE_ENV=production
    - STAGE=preproduction
    - HOST=dev.ntgdt.com
    script:
    - npm install --only=dev --force-online
    - npm run deploy:pre
  - stage: deploy PRO
    if: branch = master AND NOT type = pull_request
    env:
    - NODE_ENV=production
    - STAGE=production
    - HOST=ntgdt.com
    script:
    - npm run deploy:pro
